// A curated list of real Spotify genres for the manual genre picker.
//
// Spotify no longer reliably exposes artist genres via the API (the field is
// deprecated / empty for most indie artists), so admins often set genres by
// hand. This list is based on Spotify's official genre seeds, humanised and
// expanded with common contemporary genres so the picker offers recognisable,
// real-world Spotify genres. The field stays free-text, so anything not here can
// still be typed in.

export const SPOTIFY_GENRES: string[] = [
  "Acoustic",
  "Afrobeat",
  "Afrobeats",
  "Alternative",
  "Alt-Rock",
  "Ambient",
  "Americana",
  "Amapiano",
  "Anime",
  "Bass House",
  "Bedroom Pop",
  "Big Room",
  "Black Metal",
  "Bluegrass",
  "Blues",
  "Bossa Nova",
  "Breakbeat",
  "Chillout",
  "Chillhop",
  "Chillwave",
  "Classical",
  "Club",
  "Country",
  "Dance",
  "Dance Pop",
  "Dancehall",
  "Death Metal",
  "Deep House",
  "Disco",
  "Downtempo",
  "Dream Pop",
  "Drill",
  "Drum & Bass",
  "Dub",
  "Dubstep",
  "EDM",
  "Electro",
  "Electronic",
  "Electropop",
  "Emo",
  "Folk",
  "Folk Pop",
  "Funk",
  "Future Bass",
  "Garage",
  "Gospel",
  "Goth",
  "Grime",
  "Grunge",
  "Hard Rock",
  "Hardcore",
  "Hardstyle",
  "Heavy Metal",
  "Hip-Hop",
  "House",
  "IDM",
  "Indie",
  "Indie Folk",
  "Indie Pop",
  "Indie Rock",
  "Industrial",
  "J-Pop",
  "Jazz",
  "Jazz Fusion",
  "K-Pop",
  "Latin",
  "Lo-Fi",
  "Lo-Fi Beats",
  "Lo-Fi Hip-Hop",
  "Melodic House",
  "Melodic Techno",
  "Metal",
  "Metalcore",
  "Minimal Techno",
  "Neo-Soul",
  "New Age",
  "New Wave",
  "Pop",
  "Pop Punk",
  "Pop Rap",
  "Post-Punk",
  "Post-Rock",
  "Progressive House",
  "Psychedelic",
  "Psytrance",
  "Punk",
  "R&B",
  "Rap",
  "Reggae",
  "Reggaeton",
  "Rock",
  "Rock & Roll",
  "Singer-Songwriter",
  "Ska",
  "Soul",
  "Soundtrack",
  "Synthpop",
  "Synthwave",
  "Tech House",
  "Techno",
  "Trance",
  "Trap",
  "Trip-Hop",
  "UK Drill",
  "UK Garage",
  "World",
];
